### ISSUE TITLE
lodash and bundle size

### ISSUE THREAD

**Issue by mihap** [gajus/youtube-player#34] opened 2017-01-12 16:11 UTC
whole lodash is included into build:

node_modules/youtube-player/dist/index.js
```'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _lodash = require('lodash');

var _lodash2 = _interopRequireDefault(_lodash);

```
version: 4.0.2

**Comment by gajus** [comment] 2017-01-13 10:46
Thats odd. The build step definitely includes lodash plugin.

https://github.com/gajus/youtube-player/blob/d000e1b785fbc5e9f19bdb60117273bc95511adf/.babelrc#L3

Are you sure the source is of v4.0.2?

**Comment by mihap** [comment] 2017-01-13 10:57
yes.
cat node_modules/youtube-player/package.json | grep version
"version": "4.0.2"

I see babel-plugin-lodash was deleted from v4.0.2

**Comment by aaugustin** [comment] 2017-01-14 21:53
This issue still happens for me as well.

I expected it to be fixed in 4.0.2 after #29 and #30 (the corresponding change to package.json wasn't pushed to master in this repository, I assume it's a later commit) but no luck.

**Comment by aaugustin** [comment] 2017-01-14 22:05
Checking out master (currently @ d000e1b785fbc5e9f19bdb60117273bc95511adf), installing requirements and executing `npm run build` results in a correct `dist/index.js` file.

It looks like 4.0.2 may have been released from a branch forked from an earlier version of the code. Here are the changes between the current version of package.json and the versions in the commit from which 4.0.2 was created:

```diff
--- package.json	2017-01-14 22:58:58.000000000 +0100
+++ node_modules/youtube-player/package.json	2016-12-09 14:36:21.000000000 +0100
@@ -13,25 +13,21 @@
   "dependencies": {
     "load-script": "^1.0.0",
     "lodash": "^4.3.0",
-    "sister": "^3.0.0",
-    "youtube-player": "^4.0.2"
+    "sister": "^3.0.0"
   },
   "description": "YouTube IFrame Player API abstraction.",
   "devDependencies": {
     "ava": "^0.16.0",
     "babel-cli": "^6.18.0",
     "babel-plugin-add-module-exports": "^0.2.1",
-    "babel-plugin-lodash": "^3.2.11",
     "babel-plugin-transform-flow-comments": "^6.17.0",
     "babel-plugin-transform-object-rest-spread": "^6.16.0",
-    "babel-plugin-transform-runtime": "^6.15.0",
-    "babel-preset-env": "0.0.9",
+    "babel-preset-es2015": "^6.18.0",
     "babel-register": "^6.18.0",
     "chai": "^3.5.0",
-    "eslint": "^3.10.2",
-    "eslint-config-canonical": "^5.5.0",
+    "eslint": "^3.9.1",
+    "eslint-config-canonical": "^5.4.0",
     "husky": "^0.11.9",
-    "npm-watch": "^0.1.6",
     "semantic-release": "^6.3.2"
   },
   "keywords": [
@@ -40,7 +36,6 @@
     "player",
     "api",
     "promise",
-    "async",
     "video"
   ],
   "license": "BSD-3-Clause",
@@ -50,15 +45,11 @@
     "type": "git",
     "url": "https://github.com/gajus/youtube-player"
   },
-  "watch": {
-    "test": "{src,test}/*.js"
-  },
   "scripts": {
     "build": "NODE_ENV=production babel ./src --out-dir ./dist --copy-files",
     "lint": "eslint ./src ./test",
-    "watch": "npm-watch",
     "precommit": "npm run lint && npm run test",
     "test": "NODE_ENV=development ava --verbose && npm run lint && npm run build"
   },
-  "version": "4.0.1"
-}
+  "version": "4.0.2"
+}
\ No newline at end of file
```

Clearly the changes from https://github.com/gajus/youtube-player/commit/d000e1b785fbc5e9f19bdb60117273bc95511adf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 are missing in 4.0.2.

**Comment by gajus** [comment] 2017-01-15 16:22
Ought to be fixed in https://github.com/gajus/youtube-player/tree/v4.1.0.

**Closed by gajus** 2017-01-15 16:22 UTC
Labels: enhancement

**Comment by aaugustin** [comment] 2017-01-15 18:51
Confirmed fixed, thanks a lot for the quick response!
